Initial commit

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -1,23 +1,42 @@
 #!/usr/bin/env bash
 # manages manage_my_process
-if [ "${1}" == "start" ]
-then  
-   ./manage_my_process &
-    touch /var/run/my_process.pid
-    echo "$!" > /var/run/my_process started"
-elif [ "${1}" == "stop" ]
+# Check if an argument is provided
+if [ -z "$1" ];
 then
-    echo "manage_my_process stopped"
-    kill "$(cat /var/run/my_process.pid)"
-    rm /var/run/my_process.pid
-elif [ "${1}" == "restart" ]
-then
-    kill "$(cat /var/run/my_process.pid)"
-    rm /var/run/my_process.pid
-    ./manage_my_process &
-    touch /var/run/my_process.pid
-    echo "$!" > /var/run/my_process.pid
-    echo "manage_my_process restarted"
-else
-    echo "Usage: manage_my_process {start|stop|restart}"
+    echo "Usage: $0 {start|stop|restart}"
+    exit 1
 fi
+
+# Check the provided argument
+case "$1" in
+    start)
+        ./manage_my_process &
+        echo "$!" > /var/run/my_process.pid
+        echo "manage_my_process started"
+        ;;
+    stop)
+        echo "manage_my_process stopped"
+        if [ -f /var/run/my_process.pid ]; 
+	then
+            kill "$(cat /var/run/my_process.pid)"
+            rm /var/run/my_process.pid
+        else
+            echo "PID file not found. manage_my_process might not be running."
+        fi
+        ;;
+    restart)
+        if [ -f /var/run/my_process.pid ]; then
+            kill "$(cat /var/run/my_process.pid)"
+            rm /var/run/my_process.pid
+        fi
+        ./manage_my_process &
+        echo "$!" > /var/run/my_process.pid
+        echo "manage_my_process restarted"
+        ;;
+    *)
+        echo "Usage: $0 {start|stop|restart}"
+        exit 1
+        ;;
+esac
+
+exit 0
